name: PhysicalShop
main: com.wolvereness.physicalshop.PhysicalShop
version: ${project.version}
url: ${project.url}
softdepend: [LogBlock, LWC, Lockette]
url: http://dev.bukkit.org/server-mods/physicalshop/
commands:
   physicalshop:
      description: Reloads the configuration
authors:
    - Wolvereness